name: 🍎 macOS Builds
on:
  push:
    branches: [ master, github_actions ]
  pull_request:
    branches: [ master ]
# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: "macos-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor, tests=yes)
            cache-name: mac-editor-cache
            target: editor

          - name: Template (target=template_release)
            cache-name: macos-template
            target: template_release
            sconsflags: debug_symbols=no

    steps:
      - uses: actions/checkout@v4
        with:
          repository: godotengine/godot

      - uses: actions/checkout@v4
        with:
          path: modules/rwkv

        # init submodules in the rwkv module
      - name: Init submodules
        run: |
          cd modules/rwkv
          git submodule update --init --recursive
          cd ../..



      - name: Load .scons_cache directory
        id: godot-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}-${{ matrix.target }}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}-${{ matrix.target }}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Setup Vulkan SDK
        run: |
          sh misc/scripts/install_vulkan_sdk_macos.sh

      - name: Compilation
        env:
          SCONS_CACHE: ${{ steps.godot-cache.outputs.scons-cache }}
        run: |
          scons arch=arm64 target=${{ matrix.target }} ${{ matrix.sconsflags }} -j4

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: bin/